services:

  app:
    build: .
    ports:
      - "80:80"

  db-postgres:
    image: postgres
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: hex-rust
      POSTGRES_PASSWORD: hex-rust
