# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "contexts/src/users/intrastructure/diesel/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "D:\\programing\\learning\\rust\\rust-hexagonal-architecture\\migrations"
