### This registers a new user
POST http://localhost/users/register
Content-Type: application/json

{
  "uuid": "502a4237-ddcd-7ab3-ac03-68587d2c3d65",
  "name": "John Doe Horrible",
  "password": "password_123",
  "email": "john.doe@example.com"
}

### Gets all the users
GET http://localhost/users

### Gets all the users matching Criteria
GET http://localhost/users?offset=0
    &filters[1].field=name
    &filters[1].operator=co
    &filters[1].value=John Doe
    &order.ty=DESC
    &order.field=id

### Get only one user by id
GET http://localhost/users/502a4233-ddcd-7ab3-ac03-68587d2c3d65

### Update a user (Identifiers are inmutable)
PUT http://localhost/users/
Content-Type: application/json

{
  "uuid": "502a4267-ddcd-4ab3-ac03-68587d2c3d65",
  "name": "Jane Doe Not Especial"
}

### Deletes a user by id
DELETE http://localhost/users/502a4267-ddcd-4ab3-ac03-68587d2c3d65
