### This registers a new user
POST http://localhost:8000/users/register
Content-Type: application/json

{
  "uuid": "502a4267-ddcd-4ab3-ac03-68587d2c3d65",
  "name": "John Doe Especial",
  "password": "password123",
  "email": "john.doe@example.com"
}

### Gets all the users
GET http://localhost:8000/users

### Get only one user by id
GET http://localhost:8000/users/502a4267-ddcd-4ab3-ac03-68587d2c3d65

### Update a user (Identifiers are inmutable)
PUT http://localhost:8000/users/
Content-Type: application/json

{
  "uuid": "502a4267-ddcd-4ab3-ac03-68587d2c3d65",
  "name": "Jane Doe Not Especial",
  "password": "newpassword123",
  "email": "jane.doe@example.com"
}

### Deletes a user by id
DELETE http://localhost:8000/users/502a4267-ddcd-4ab3-ac03-68587d2c3d65
